---
apiVersion: v1
kind: Service
metadata:
  name: service-pastry-consumer
  namespace: service-pastry-consumer
  labels:
    app: service-pastry-consumer
    subsystem: app
spec:
  ports:
    - name: https
      port: 8000
  selector:
    app: service-pastry-consumer
    subsystem: app
  type: ClusterIP